config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :feedbacks, shallow: true, only: %i[new create]
  resources :tests, shallow: true, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index show]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users

  validates :name, uniqueness: true
  validates :file_name, presence: true

  def file_url
    File.join('badges_images', file_name)
  end

  def give_away?(test_passage)
    return NotImplementedError
  end

  def self.badges_types
    Dir["#{File.dirname(__FILE__)}/badges/*.rb"].each { |file| load file }
    Badges.constants.select { |c| Badges.const_get(c).is_a? Class }.sort!
  end
end

app/models/badges/first_attempt_passed_test_badge.rb
class Badges::FirstAttemptPassedTestBadge < Badge
  def give_away?(test_passage)
    test_passages = test_passage.user.test_passages.where(test_id: test_passage.test.id)
    test_passages.count == 1 && test_passages.first.succeed?
  end
end

app/models/badges/first_passed_test_badge.rb
class Badges::FirstPassedTestBadge < Badge
  def give_away?(test_passage)
    passed_tests = 0
    test_passage.user.test_passages.where(test_id: test_passage.test.id).each do |t_p|
      passed_tests += 1 if t_p.succeed?
      break if passed_tests >= 2
    end
    passed_tests == 1 && test_passage.succeed?
  end
end

app/models/badges/test_completed_for_level.rb
class Badges::TestCompletedForLevel < Badge
  def give_away?(test_passage)
    user_tests_for_level = test_passage.user.completed_tests.where(level: test_passage.test.level)
    all_test_for_level = Test.where(level: test_passage.test.level)

    (user_tests_for_level.count == all_test_for_level.count) && TestPassage.where(test: test_passage.test, passed: true).count == 1
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :authenticate_user!
  before_action :find_badge, only: %i[edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    # badge_params[:type] = 'Badges::' + badge_params[:type].to_s
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit; end

  def update
    # badge_params[:type] = 'Badges::' + badge_params[:type].to_s
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :file_name, :type)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_badges = current_user.badges.all
    @badges = Badge.all
  end

  def show; end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badges_types_array_for_select
    # Badge.badges_types.map.with_index(0) { |type, i| [type, i] }
    Badge.badges_types.map { |type| [ type, "Badges::#{type}"] }
  end

  def show_new_badges_msg(new_badges_array)
    unless new_badges_array.empty?
      new_badges_msg = new_badges_array.map { |b| "Вы получили медаль '#{b.name}' " }.join("\n")
      flash.now[:notice] = new_badges_msg
    end
  end
end

app/views/admin/badges/_badge.html.slim
tr
  th scope="row" class="align-middle" = badge.name
  td class="align-middle" = image_tag badge.file_url, size: "32"
  td class="align-middle" = button_to 'Edit', edit_admin_badge_path(badge), class: "btn btn-warning", method: :get
  td class="align-middle" = button_to 'Delete', admin_badge_path(badge), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

app/views/admin/badges/_form.html.slim
= bootstrap_form_with model: [:admin, @badge.becomes(Badge)], local: true do |form|
  = render 'shared/errors', resource: @badge

  p
    = form.text_field :name

  p
    = form.text_field :file_name

  p
    = form.select :type, options_for_select(badges_types_array_for_select)

  = form.submit


br
= link_to "Назад", admin_badges_path

app/views/admin/badges/edit.html.slim
div class="mt-3"
  h1 Изменить бейдж

= render 'form'

app/views/admin/badges/index.html.slim
div class="mt-3"
  h1 = "Доступные Бейджи"

p
  = button_to 'Создать Бейдж', new_admin_badge_path, class: "btn btn-success", method: :get

p
  = render 'shared/errors', resource: @badge

table class="table"
  thead
    tr
      th scope="col" Название
      th scope="col" Значок
      th scope="col" colspan="2" Действия

  = render partial: 'badge', collection: @badges

app/views/admin/badges/new.html.slim
div class="mt-3"
  h1 Создать новый бейдж

= render 'form'