config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :feedbacks, shallow: true, only: %i[new create]
  resources :tests, shallow: true, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index show]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  COMPLETION_THRESHOLD = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update
  after_validation :after_validation_check_if_test_passed, on: :update
  before_create :after_create_set_expire_time

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def success_percent
    (100 / test.questions.count) * correct_questions
  end

  def succeed_or_failed
    if success_percent >= COMPLETION_THRESHOLD
      :succeed
    else
      :failed
    end
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def succeed?
    success_percent >= COMPLETION_THRESHOLD && completed?
  end

  def time_left_to_pass
    self.expire_time - Time.now
  end

  private

  def correct_answer?(answer_ids)
    answer_ids.reject!(&:empty?)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def after_create_set_expire_time
    if test.passage_time > 0
      self.expire_time = test.passage_time.minutes.from_now
      puts expire_time
    else
      self.expire_time = nil
    end
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def after_validation_check_if_test_passed
    self.passed = true if completed?
  end
end

app/controllers/test_passages_controller.rb
require_relative '../services/gist_question_service'
require_relative '../services/badge_service'

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show update result gist]

  def show
    if @test_passage.expire_time
      redirect_to result_test_passage_path(@test_passage) if @test_passage.expire_time < Time.now
    end
  end

  def result
    new_badges = BadgeService.new(@test_passage).call
    helpers.show_new_badges_msg(new_badges)
  end

  def gist
    @result   = GistQuestionService.new(@test_passage.current_question).call
    @gist_url = @result[:html_url]
    if Octokit.last_response
      flash_options = { alert: t('.failure') }
    else
      current_user.gists.create(url: @result[:id], question: @test_passage.current_question)
      flash_options = { notice: t('.success_html', url: view_context.link_to(t('.gist_href'), @gist_url, class: "alert-link")) }
    end

    redirect_to @test_passage, flash_options
  end

  def update
    return redirect_to result_test_passage_path(@test_passage) if @test_passage.expire_time < Time.now
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def seconds_to_time(seconds)
    [(seconds / 3600).floor, (seconds / 60 % 60).floor, (seconds % 60).floor].map { |t| t.to_s.rjust(2,'0') }.join(':')
  end
end

app/views/test_passages/result.html.slim
h3 id="#{@test_passage.succeed_or_failed}_message" class="#{@test_passage.succeed? ? 'text-success' : 'text-danger'}"
  = t(".#{@test_passage.succeed_or_failed}", title: @test_passage.test.title)

br
a = link_to 'More tests', tests_path

app/views/test_passages/show.html.slim
h1 Passing the #{@test_passage.test.title} Test
- if @test_passage.expire_time
  h3 = content_tag :span, class: "badge badge-warning" do
    | Time left: #{seconds_to_time(@test_passage.time_left_to_pass)}

b
  | Question #{@test_passage.current_question_number} of #{@test_passage.test.questions.count}:

  br
  | "#{@test_passage.current_question.body}"

== form_with url: test_passage_path(@test_passage),
        local: true,
        method: :put do |form|

  == form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: true do |b|
    p
      = b.check_box id: "answer_ids_#{b.object.id}"
      = b.label

  p
    = link_to 'Gist this question', gist_test_passage_path(@test_passage), method: :post
  p
    = form.submit 'Next'

  = content_tag :div, class: "progress" do
    = content_tag :div, class: "progress-bar bg-success",
      data: { question_number: @test_passage.current_question_number, questions_count: @test_passage.test.questions.count } do