config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :feedbacks, shallow: true, only: %i[new create]
  resources :tests, shallow: true, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index show]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.present?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do
    h2 = t '.header', count: resource.errors.count

    ul
      - resource.errors.full_messages.each do |message|
        li = message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  div class="alert #{bootstrap_class_for_flash(key)} alert-dismissible fade show mt-3"
    = raw message

app/views/shared/_footer.html.slim
.footer
    br
    | Copyright &copy
    = year
    =< github_url "Codcore", "Test-Guru"
    br
    | Developed by Andrew Mark. #{link_to t('.feedback'), new_feedback_path}
    br
    | Test-Guru is a service for publishing and surveying online tests.
    br
    | Training project at
    a< href="http://thinknetica.com" Thinknetica online school

app/views/shared/_nav.html.slim
nav class="navbar navbar-light bg-light"
  = link_to 'TestGuru', root_path, class: 'navbar-brand'

  span class="navbar-text"
    - if user_signed_in?
      | #{t '.welcome'},
      b #{link_to current_user.first_name, badges_path} | #{link_to 'Log out', destroy_user_session_path, method: :delete}
      br
      - if current_user.admin?
        = link_to "[ Admin panel ]", admin_tests_path
        = link_to "[ Gists ]", admin_gists_path
        = link_to "[ Badges ]",  admin_badges_path

    - else
      ' #{link_to t('.register'), new_user_registration_path} |
      ' #{link_to t('.login'), user_session_path}