config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  resources :feedbacks, shallow: true, only: %i[new create]
  resources :tests, shallow: true, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index show]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :authenticate_user!
  before_action :find_test, only: %i[create index new]
  before_action :find_question, only: %i[show destroy edit update]

  # rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def edit; end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  def new
    @question = @test.questions.new
  end

  def create
    question = @test.questions.new(question_params)
    if question.save
      redirect_to admin_question_path(question)
    else
      response.status = 400
      render plain: 'Bad Request'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    response.status = 404
    render plain: 'Question not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    action = question.new_record? ? 'Create new' : 'Edit'
    "#{action} question for test \"#{question.test.title}\""
  end
end

app/views/admin/questions/_form.html.slim
= form_with model: [:admin, @test, @question], local: true do |form|
  = render 'shared/errors', resource: @question

  p
    = form.label :body
    br
    = form.text_field :body

  = form.submit

br

app/views/admin/questions/_question.html.slim
tr
  td = question.body
  td  = link_to t('.edit'), edit_admin_question_path(question)
  td = link_to t('.show'), admin_question_path(question)
  td = link_to t('.delete'), admin_question_path, method: :delete, data: { confirm: t('.sure') }

app/views/admin/questions/_test_questions.html.slim
table
  tr
    th Question
    th colspan="3" Actions

    = render partial: 'admin/questions/question', collection: @test.questions

app/views/admin/questions/edit.html.slim
h1 = question_header(@question)

= render 'form'
= link_to 'Back', admin_test_path

app/views/admin/questions/index.html.slim
h1 = @test.title
ul
  - @test.questions.each do |q|
    li = q.body
    = link_to "x", admin_question_path(q), method: :delete, data: { confirm: "Are you sure?" }

app/views/admin/questions/new.html.slim
h1 = question_header(@question)

= render 'form'
= link_to 'Back', admin_test_path(@test)

app/views/admin/questions/show.html.slim
h1 #{@question.test.title} Question

p
  = @question.body

h2 Answers

= link_to 'New answer', new_admin_question_answer_path(@question)

ol
  = render partial: 'admin/answers/answer', collection: @question.answers

=> (link_to 'Edit', edit_admin_question_path(@question))
'|
=> (link_to 'Delete', admin_question_path, method: :delete, data: { confirm: 'Are you sure?' })
'|
=> link_to 'Back', admin_test_path(@question.test)